:PROPERTIES:
:ID:       68be6ff4-f800-4a86-8da7-d57f35e5a0cc
:END:
#+title: AI經濟的策略思維
#+filetags: :深度學習:

* AI經濟學
- 第一波的[[id:20221023T101138.945879][人工智慧]]並沒有真正帶來智慧，而是帶來智慧中的一個關鍵成分：預測。
- Chisel藉由預測文件的哪個些部份要編修，來改善法律實務
- 最好的AI策略或工具是什麼，這個問題並沒有唯一的正確答案，因為AI牽涉到權衡取捨；速度愈快，準確度愈低；自動化愈高，操控愈少；數數愈多，隱私愈少。
- 當某個非常基本的東西價格大幅下降，整個世界就會改變。同樣亮度的照明，在1800年代初期付出的費用可能是現在的400倍，照明的成本下跌如此多，改變了我們的行為，從思考要不要用，變成不假思索打開電燈。當計算變的更便宜，我們不但會進行更多傳統的計算應用，還會將剛變的便宜的計算用在與傳統計算無關的應用，例如音樂。
- 那麼....當預測變的很便宜時會發生什麼改變?這是我們要極力思考的，因為AI科技會把預測變的很便宜，和現在的照明一樣便宜？我要如何從中找出其獲利模式？商機何在？
- 當某個東西的價格下跌，我們就會用的更多。這是簡單的經濟學，而且正是此刻AI的狀況：AI隨處可見，充斥在手機應用程式中，使供電系統優化，並取代基金經理人[fn:1]。
- 什麼是預測：利用你擁有的資訊，產生出你沒有的資訊。
- 什麼是「AI洞見」(AI Insight): 看到問題並將問題重新組合為一個預測問題的能力[fn:2]。
- 什麼是「互補品」(complement): 當某些東西的成本下降(如咖啡)，可能會有東西的價格會提高(如糖與奶精)。當「預測」這個生產因素變便宜時，什麼東西的價格會提高呢？答案是「數據」。
** 預測平價後的新策略
- 當AI的預測準確率跨過一個門檻，Amazon的商業模式也隨之改變，對Amazon來說，當預測夠準確，更划算的作法就是不等你訂貨，就可以預測到你會想買的東西，直接出貨給你，從「購物後出貨(Shopping-then-shipping)」變成「出貨後購物(shipping-then-shopping)」。Amazon已在2013年取得「預期性出貨(anticipatory shipping)[fn:3]。

* 深度學習 v.s. 迴歸模型
杜克大學Teradata中心在2004年舉辦一場預測顧客流失率的數據科學大賽。當年的優勝者使用[[id:6ae7fb7a-0b38-4448-b19f-073d262513f2][迴歸]]模型，到了2016年情況就改變了，預測顧客流失率最好的模型就是使用[[id:20221023T101456.955364][機器學習]]，而且（[[id:d6daa102-05bb-475d-b619-db8b61e86030][神經網路]]）[[id:20221023T101228.247381][深度學習]]的表現普遍比其他模型好。

原因：在1990年代很難建立夠大的數據庫，典型的顧客流失率預測會使用650個顧客、30個以下的變數。到了2004年，電腦處理和儲存功能已有改變，訓練數據庫裡的資訊已有幾千個顧客和幾百個變數。

成功的關鍵要素是：
1. 挑選特徵值：從數百的現有的變數中選擇要納入哪些變數
2. 挑模型: 選擇要使用哪一種統計模型

* 資料
- 為了做出優異的預測，機器的訓練數據必須有足夠的個體（分析單位）。其個體數取決於兩個因素：
  1. 「信號」相對於「雜訊」的可靠程度；
  2. 預測必須多準確才有用處？

* 機器不擅長的預測
- 美國前國防部長唐納德．倫斯斐(Donald Rumsfeld)曾說：「有些事是已知的已知(known knowns)，這些是我們知道自己知道的事；我們還知道有些已知的未知(known unknowns)，就是我們知道自己不知道的事；但還有未知的已知(unknown unknowns)，我們不知道自己不知道的事。

** KK/UK/KU/UU
|---------+-------+---------|
|         | known | unknown |
|---------+-------+---------|
| known   | KK    | KU      |
| unknown | UK    | UU      |
|---------+-------+---------|
*** KK: 已知的未知
有豐富的數據，機器預測就能順利運作，這是目前的AI最有效的地方，如詐騙偵測、醫療診斷、棒球選手篩選與交保決定。
*** KU: 已知的未知
缺乏太多數據，也許是因為事情罕見，例如總統大選，或是大地震。相對於機器，人類有時擅長以稀少的數據做預測。我們可以在看過一、兩次就認出一張臉（過目不忘），即便是從不同角度看
*** UK: 未知的已知
*** UU: 未知的未知

* Footnotes

[fn:3] P.37
[fn:2] Integrate.ai的凱斯琳。賀威(Kathryn Howe)

[fn:1] P24
